services:
  travel-booking-backend:
    build: ..
    environment:
      - ConnectionStrings__StoreContext=Host=travel-booking-db;Username=postgres;Password=postgres;Database=travelbooking
    volumes:
      - misc_data:/root/.aspnet
    ports:
      - 8080:5000
    depends_on:
      - travel-booking-db
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost/api/health || exit 1" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.passenger-api.rule=Host(`passenger.foxelyss.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.passenger-api.entrypoints=websecure"
      - "traefik.http.routers.passenger-api.tls=true"
      - "traefik.http.routers.passenger-api.tls.certresolver=le"
      - "traefik.http.routers.passenger-api.middlewares=passenger-headers"
      - "traefik.http.routers.passenger-api.service=passenger-api-service"
      - "traefik.http.services.passenger-api-service.loadbalancer.server.port=3300"
      - "traefik.http.services.passenger-api-service.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.passenger-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.passenger-headers.headers.accessControlAllowOrigin=`https://passenger.foxelyss.ru`"

    networks:
      - travel
      - mega-main

  travel-booking-db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=travelbooking
    volumes:
      - db_data:/var/lib/postgresql/
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: unless-stopped
    networks:
      - travel

volumes:
  misc_data:
  db_data:


networks:
  travel:
  mega-main:
    external: true
    name: mega-network
