name: Integration Tests

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      ConnectionStrings__StoreContext: "Host=localhost;Port=5432;Database=testdb;Username=postgres;Password=password"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://localhost:5165

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef --version 9.0.10

      - name: Apply EF migrations
        run: dotnet ef database update --project src/TravelBooking.csproj --no-build

      - name: Start API server
        uses: miguelteixeiraa/action-run-in-background@v1
        with:
          script: |
            # run some blocking stuff
            dotnet run --project src/TravelBooking.csproj

          readiness-script: |
            # check if whatever is it to run, is ready
            if curl -sSf http://localhost:5165/ > /dev/null; then
                echo "curl request was successful."
            else
                echo "curl request failed."
                exit 1
            fi

          shell: bash
          timeout: 30

      - name: Setup Node (required for Bruno)
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
      
      - name: Create reports directory
        run: mkdir -p reports

      - name: Seed tests
        run: node tests/seed.js
      
      - name: Run Bruno tests
        env:
          HOST: http://localhost:5165
        run: cd tests/integration && bru run --env-var host=$HOST --json-file-path data.json --reporter-html ../../reports/results.html --reporter-junit ../../reports/results.xml
        continue-on-error: true

      - name: Upload Bruno test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: reports/
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          report_individual_runs: "true"
          files: |
            reports/results.xml
    
      - name: Stop API server
        run: |
          echo "Shutting down API..."
          # Kill the background dotnet process started earlier
          pkill -f "dotnet run" || true